
# PALAUTE: KOODI TOIMII NIIN KUIN PITÄÄKIN, MUTTA EN SUSOITTELE KÄYTTÄMÄÄN KOLMEA LAINAUSMERKKIÄ 'NORMAALEIDEN' MUUTTUJIEN TULOSTAMISEEN / LUOMISEEN
# KOLME LAIANUSMERKKIÄ ON NS. DOCSTRING, JOSTA MONET TYÖKALUT GENEROIVAT DOKUMENTAATION AUTOM.
# JOS SINULLA ON DOCSTRINGISSÄ MUUTTUJIEN ARVOJA, NE TULEVAT MUKAAN DOKUMENTAATIOON

# HYVÄKSYN TEHTÄVÄN, KOSKA TÄTÄHÄN EI OLE TEHTÄVÄNANNOSSA KIELLETTY

hello = "Hello World!" #ensimmäinen muuttuja
nimi = """Miklas Kulmala
1982
Ojakatu 16 A 2, 03600 Karkkila""" #toinen muuttuja

#luodaan tulostetaan muuttujat hello ja nimi

print(hello)
print(nimi)